#!/bin/bash

echo "🖼️  VELOCITY WORKFORCE MANAGEMENT - SCREENSHOT VIEWER"
echo "====================================================="
echo ""
echo "Total Screenshots: 24"
echo "Location: test-results/"
echo ""
echo "OPTIONS:"
echo "--------"
echo ""
echo "1. View Interactive HTML Report (Recommended):"
echo "   pnpm exec playwright show-report"
echo "   (Opens browser with all screenshots + test details)"
echo ""
echo "2. List All Screenshot Files:"
echo "   find test-results -name '*.png' | sort"
echo ""
echo "3. Open Specific Screenshots:"
echo "   - Dashboard: test-results/routes-audit-Route-Audit---All-93-Routes-Route---Dashboard-chromium/test-finished-1.png"
echo "   - Contractors: test-results/routes-audit-Route-Audit---94983-tractors---Contractors-List-chromium/test-finished-1.png"
echo "   - AI Insights (FAILED): test-results/routes-audit-Route-Audit---a3c8a-e-ai-insights---AI-Insights-chromium/test-failed-1.png"
echo ""
echo "4. Copy All Screenshots to a Folder:"
echo "   mkdir -p all-screenshots && find test-results -name '*.png' -exec cp {} all-screenshots/ \;"
echo ""
echo "For full catalog, see: COMPLETE_SCREENSHOT_CATALOG.md"
